schema_version: 1

context:
  name: tango-access-control
  version: "2.22"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://gitlab.com/tango-controls/TangoAccessControl/-/releases/TangoAccessControl-Release-${{ version }}/downloads/TangoAccessControl-with-submodules-TangoAccessControl-Release-${{ version }}.tar.gz
  sha256: ced23d8f264d52590e607bb35ac3a49efe1f59f45b9b7dfbf6b9340e1eca3653

build:
  number: 2

requirements:
  build:
    - cmake
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: unix
      then:
        - make
        - pkg-config
  host:
    - cppzmq
    - cpptango
    - mysql-devel
    - omniorb-libs
  run:
    # mysql-client is required to install "lib/plugin/mysql_native_password.so"
    - mysql-client

tests:
  - script:
      - if: unix
        then: TangoAccessControl --help 2>&1 | grep -i usage
        else: TangoAccessControl.exe --help 2>&1 | findstr /i usage

about:
  summary: Tango Access Control device server
  description: |
    This is the device server used to run a Tango control system
    with controlled access.
    Tango-Controls is a software toolkit for building control systems.
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://www.tango-controls.org
  repository: https://gitlab.com/tango-controls/TangoAccessControl

extra:
  recipe-maintainers:
    - beenje
